# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_desk.ipynb.

# %% auto 0
__all__ = ['Deck', 'draw_n']

# %% ../nbs/02_desk.ipynb 2
from nbdev_cards.card import *
from fastcore.utils import *
import random

# %% ../nbs/02_desk.ipynb 4
class Deck:
    "A deck of 52 cards, not including jokers"
    def __init__(self): 
        self.cards = [Card(s,r) for s in range(4) for r in range(1,14)]
    def __len__(self):
        return len(self.cards)
    def __str__(self):
        return '; '.join(map(str, self.cards))
    def __contains__(self, card):
        return card in self.cards
    __repr__ = __str__
    
    def shuffle(self):
        "Shuffles the cards in this deck"
        random.shuffle(self.cards)

# %% ../nbs/02_desk.ipynb 13
@patch
def pop(self: Deck,
       idx: int=-1):  # The index of the card to remove, defaulting to the last one
    "Remove one card from the deck"
    return self.cards.pop(idx)

# %% ../nbs/02_desk.ipynb 17
@patch
def remove(self: Deck,
          card: Card):  # Card to remove
    "Remove `card` from the deck or raises exeption if it is not there"
    return self.cards.remove(card)

# %% ../nbs/02_desk.ipynb 20
def draw_n(n: int, # number of the cards to draw
          replace: bool=true): # whether or not draw with replacement
    "Draw `n` cards, with replacement if `replace`"
    d = Deck()
    d.shuffle()
    if replace:
        return [d.cards[random.choice(range(len(d.cards)))] for _ in range(n)]
    else:
        return d.cards[:n]
